services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: meal-maker-db
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
  cache:
    driver: local
